build_skia_mac_task:
  only_if: changesInclude('.cirrus.yml', '.cirrus/build_skia_mac.sh')
  osx_instance:
    image: mojave-xcode-10.2
  script: .cirrus/build_skia_mac.sh
  artifacts: 
    path: out/Release/libskia.a.zst.*
