osx_instance:
  image: mojave-xcode-10.2

task:
  artifacts: out/Debug/libskia.a
  script: 
    - git clone 'https://chromium.googlesource.com/chromium/tools/depot_tools.git'
    - export PATH="${PWD}/depot_tools:${PATH}"
    - git clone https://skia.googlesource.com/skia.git
    - cd skia
    - python tools/git-sync-deps
    - bin/gn gen out/Debug --args='is_official_build=false'
    - tools/install_dependencies.sh
    - ninja -C out/Debug
